#docker-compose.yml
version: "3.0"
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_HOST: localhost
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: olympus_db
      POSTGRES_PASSWORD: password
